#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyThuVien")]
	public partial class QuanLyThuVienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTPM(CTPM instance);
    partial void UpdateCTPM(CTPM instance);
    partial void DeleteCTPM(CTPM instance);
    partial void InsertDAUSACH(DAUSACH instance);
    partial void UpdateDAUSACH(DAUSACH instance);
    partial void DeleteDAUSACH(DAUSACH instance);
    partial void InsertDOCGIA(DOCGIA instance);
    partial void UpdateDOCGIA(DOCGIA instance);
    partial void DeleteDOCGIA(DOCGIA instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertNHAXUATBAN(NHAXUATBAN instance);
    partial void UpdateNHAXUATBAN(NHAXUATBAN instance);
    partial void DeleteNHAXUATBAN(NHAXUATBAN instance);
    partial void InsertPHIEUMUONTRA(PHIEUMUONTRA instance);
    partial void UpdatePHIEUMUONTRA(PHIEUMUONTRA instance);
    partial void DeletePHIEUMUONTRA(PHIEUMUONTRA instance);
    partial void InsertTACGIA(TACGIA instance);
    partial void UpdateTACGIA(TACGIA instance);
    partial void DeleteTACGIA(TACGIA instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTHEDOCGIA(THEDOCGIA instance);
    partial void UpdateTHEDOCGIA(THEDOCGIA instance);
    partial void DeleteTHEDOCGIA(THEDOCGIA instance);
    partial void InsertTHELOAI(THELOAI instance);
    partial void UpdateTHELOAI(THELOAI instance);
    partial void DeleteTHELOAI(THELOAI instance);
    #endregion
		
		public QuanLyThuVienDataContext() : 
				base(global::QuanLyThuVien.Properties.Settings.Default.QuanLyThuVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTPM> CTPMs
		{
			get
			{
				return this.GetTable<CTPM>();
			}
		}
		
		public System.Data.Linq.Table<DAUSACH> DAUSACHes
		{
			get
			{
				return this.GetTable<DAUSACH>();
			}
		}
		
		public System.Data.Linq.Table<DOCGIA> DOCGIAs
		{
			get
			{
				return this.GetTable<DOCGIA>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<NHAXUATBAN> NHAXUATBANs
		{
			get
			{
				return this.GetTable<NHAXUATBAN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUMUONTRA> PHIEUMUONTRAs
		{
			get
			{
				return this.GetTable<PHIEUMUONTRA>();
			}
		}
		
		public System.Data.Linq.Table<TACGIA> TACGIAs
		{
			get
			{
				return this.GetTable<TACGIA>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<THEDOCGIA> THEDOCGIAs
		{
			get
			{
				return this.GetTable<THEDOCGIA>();
			}
		}
		
		public System.Data.Linq.Table<THELOAI> THELOAIs
		{
			get
			{
				return this.GetTable<THELOAI>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procSachDuocMuonNhieu")]
		public ISingleResult<procSachDuocMuonNhieuResult> procSachDuocMuonNhieu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayBatDau", DbType="VarChar(50)")] string ngayBatDau, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayKetThuc", DbType="VarChar(50)")] string ngayKetThuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngayBatDau, ngayKetThuc);
			return ((ISingleResult<procSachDuocMuonNhieuResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPM")]
	public partial class CTPM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASACH;
		
		private string _MAPHIEUMUON;
		
		private string _SOLUONG;
		
		private string _TINHTRANG;
		
		private System.Nullable<System.DateTime> _HANTRA;
		
		private System.Nullable<System.DateTime> _NGAYTRA;
		
		private EntityRef<DAUSACH> _DAUSACH;
		
		private EntityRef<PHIEUMUONTRA> _PHIEUMUONTRA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASACHChanging(string value);
    partial void OnMASACHChanged();
    partial void OnMAPHIEUMUONChanging(string value);
    partial void OnMAPHIEUMUONChanged();
    partial void OnSOLUONGChanging(string value);
    partial void OnSOLUONGChanged();
    partial void OnTINHTRANGChanging(string value);
    partial void OnTINHTRANGChanged();
    partial void OnHANTRAChanging(System.Nullable<System.DateTime> value);
    partial void OnHANTRAChanged();
    partial void OnNGAYTRAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTRAChanged();
    #endregion
		
		public CTPM()
		{
			this._DAUSACH = default(EntityRef<DAUSACH>);
			this._PHIEUMUONTRA = default(EntityRef<PHIEUMUONTRA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASACH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASACH
		{
			get
			{
				return this._MASACH;
			}
			set
			{
				if ((this._MASACH != value))
				{
					if (this._DAUSACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASACHChanging(value);
					this.SendPropertyChanging();
					this._MASACH = value;
					this.SendPropertyChanged("MASACH");
					this.OnMASACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUMUON", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHIEUMUON
		{
			get
			{
				return this._MAPHIEUMUON;
			}
			set
			{
				if ((this._MAPHIEUMUON != value))
				{
					if (this._PHIEUMUONTRA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHIEUMUONChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUMUON = value;
					this.SendPropertyChanged("MAPHIEUMUON");
					this.OnMAPHIEUMUONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Char(5)")]
		public string SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="NVarChar(10)")]
		public string TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HANTRA", DbType="DateTime")]
		public System.Nullable<System.DateTime> HANTRA
		{
			get
			{
				return this._HANTRA;
			}
			set
			{
				if ((this._HANTRA != value))
				{
					this.OnHANTRAChanging(value);
					this.SendPropertyChanging();
					this._HANTRA = value;
					this.SendPropertyChanged("HANTRA");
					this.OnHANTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTRA", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTRA
		{
			get
			{
				return this._NGAYTRA;
			}
			set
			{
				if ((this._NGAYTRA != value))
				{
					this.OnNGAYTRAChanging(value);
					this.SendPropertyChanging();
					this._NGAYTRA = value;
					this.SendPropertyChanged("NGAYTRA");
					this.OnNGAYTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAUSACH_CTPM", Storage="_DAUSACH", ThisKey="MASACH", OtherKey="MASACH", IsForeignKey=true)]
		public DAUSACH DAUSACH
		{
			get
			{
				return this._DAUSACH.Entity;
			}
			set
			{
				DAUSACH previousValue = this._DAUSACH.Entity;
				if (((previousValue != value) 
							|| (this._DAUSACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DAUSACH.Entity = null;
						previousValue.CTPMs.Remove(this);
					}
					this._DAUSACH.Entity = value;
					if ((value != null))
					{
						value.CTPMs.Add(this);
						this._MASACH = value.MASACH;
					}
					else
					{
						this._MASACH = default(string);
					}
					this.SendPropertyChanged("DAUSACH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUMUONTRA_CTPM", Storage="_PHIEUMUONTRA", ThisKey="MAPHIEUMUON", OtherKey="MAPHIEUMUON", IsForeignKey=true)]
		public PHIEUMUONTRA PHIEUMUONTRA
		{
			get
			{
				return this._PHIEUMUONTRA.Entity;
			}
			set
			{
				PHIEUMUONTRA previousValue = this._PHIEUMUONTRA.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUMUONTRA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUMUONTRA.Entity = null;
						previousValue.CTPMs.Remove(this);
					}
					this._PHIEUMUONTRA.Entity = value;
					if ((value != null))
					{
						value.CTPMs.Add(this);
						this._MAPHIEUMUON = value.MAPHIEUMUON;
					}
					else
					{
						this._MAPHIEUMUON = default(string);
					}
					this.SendPropertyChanged("PHIEUMUONTRA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DAUSACH")]
	public partial class DAUSACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASACH;
		
		private string _TENSACH;
		
		private string _NAMXUATBAN;
		
		private string _MATHELOAI;
		
		private string _MANXB;
		
		private string _MATACGIA;
		
		private EntitySet<CTPM> _CTPMs;
		
		private EntityRef<NHAXUATBAN> _NHAXUATBAN;
		
		private EntityRef<TACGIA> _TACGIA;
		
		private EntityRef<THELOAI> _THELOAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASACHChanging(string value);
    partial void OnMASACHChanged();
    partial void OnTENSACHChanging(string value);
    partial void OnTENSACHChanged();
    partial void OnNAMXUATBANChanging(string value);
    partial void OnNAMXUATBANChanged();
    partial void OnMATHELOAIChanging(string value);
    partial void OnMATHELOAIChanged();
    partial void OnMANXBChanging(string value);
    partial void OnMANXBChanged();
    partial void OnMATACGIAChanging(string value);
    partial void OnMATACGIAChanged();
    #endregion
		
		public DAUSACH()
		{
			this._CTPMs = new EntitySet<CTPM>(new Action<CTPM>(this.attach_CTPMs), new Action<CTPM>(this.detach_CTPMs));
			this._NHAXUATBAN = default(EntityRef<NHAXUATBAN>);
			this._TACGIA = default(EntityRef<TACGIA>);
			this._THELOAI = default(EntityRef<THELOAI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASACH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASACH
		{
			get
			{
				return this._MASACH;
			}
			set
			{
				if ((this._MASACH != value))
				{
					this.OnMASACHChanging(value);
					this.SendPropertyChanging();
					this._MASACH = value;
					this.SendPropertyChanged("MASACH");
					this.OnMASACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSACH", DbType="NVarChar(30)")]
		public string TENSACH
		{
			get
			{
				return this._TENSACH;
			}
			set
			{
				if ((this._TENSACH != value))
				{
					this.OnTENSACHChanging(value);
					this.SendPropertyChanging();
					this._TENSACH = value;
					this.SendPropertyChanged("TENSACH");
					this.OnTENSACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMXUATBAN", DbType="VarChar(50)")]
		public string NAMXUATBAN
		{
			get
			{
				return this._NAMXUATBAN;
			}
			set
			{
				if ((this._NAMXUATBAN != value))
				{
					this.OnNAMXUATBANChanging(value);
					this.SendPropertyChanging();
					this._NAMXUATBAN = value;
					this.SendPropertyChanged("NAMXUATBAN");
					this.OnNAMXUATBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHELOAI", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MATHELOAI
		{
			get
			{
				return this._MATHELOAI;
			}
			set
			{
				if ((this._MATHELOAI != value))
				{
					if (this._THELOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHELOAIChanging(value);
					this.SendPropertyChanging();
					this._MATHELOAI = value;
					this.SendPropertyChanged("MATHELOAI");
					this.OnMATHELOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANXB", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MANXB
		{
			get
			{
				return this._MANXB;
			}
			set
			{
				if ((this._MANXB != value))
				{
					if (this._NHAXUATBAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANXBChanging(value);
					this.SendPropertyChanging();
					this._MANXB = value;
					this.SendPropertyChanged("MANXB");
					this.OnMANXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATACGIA", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MATACGIA
		{
			get
			{
				return this._MATACGIA;
			}
			set
			{
				if ((this._MATACGIA != value))
				{
					if (this._TACGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATACGIAChanging(value);
					this.SendPropertyChanging();
					this._MATACGIA = value;
					this.SendPropertyChanged("MATACGIA");
					this.OnMATACGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAUSACH_CTPM", Storage="_CTPMs", ThisKey="MASACH", OtherKey="MASACH")]
		public EntitySet<CTPM> CTPMs
		{
			get
			{
				return this._CTPMs;
			}
			set
			{
				this._CTPMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHAXUATBAN_DAUSACH", Storage="_NHAXUATBAN", ThisKey="MANXB", OtherKey="MANXB", IsForeignKey=true)]
		public NHAXUATBAN NHAXUATBAN
		{
			get
			{
				return this._NHAXUATBAN.Entity;
			}
			set
			{
				NHAXUATBAN previousValue = this._NHAXUATBAN.Entity;
				if (((previousValue != value) 
							|| (this._NHAXUATBAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHAXUATBAN.Entity = null;
						previousValue.DAUSACHes.Remove(this);
					}
					this._NHAXUATBAN.Entity = value;
					if ((value != null))
					{
						value.DAUSACHes.Add(this);
						this._MANXB = value.MANXB;
					}
					else
					{
						this._MANXB = default(string);
					}
					this.SendPropertyChanged("NHAXUATBAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TACGIA_DAUSACH", Storage="_TACGIA", ThisKey="MATACGIA", OtherKey="MATACGIA", IsForeignKey=true)]
		public TACGIA TACGIA
		{
			get
			{
				return this._TACGIA.Entity;
			}
			set
			{
				TACGIA previousValue = this._TACGIA.Entity;
				if (((previousValue != value) 
							|| (this._TACGIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TACGIA.Entity = null;
						previousValue.DAUSACHes.Remove(this);
					}
					this._TACGIA.Entity = value;
					if ((value != null))
					{
						value.DAUSACHes.Add(this);
						this._MATACGIA = value.MATACGIA;
					}
					else
					{
						this._MATACGIA = default(string);
					}
					this.SendPropertyChanged("TACGIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THELOAI_DAUSACH", Storage="_THELOAI", ThisKey="MATHELOAI", OtherKey="MATHELOAI", IsForeignKey=true)]
		public THELOAI THELOAI
		{
			get
			{
				return this._THELOAI.Entity;
			}
			set
			{
				THELOAI previousValue = this._THELOAI.Entity;
				if (((previousValue != value) 
							|| (this._THELOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THELOAI.Entity = null;
						previousValue.DAUSACHes.Remove(this);
					}
					this._THELOAI.Entity = value;
					if ((value != null))
					{
						value.DAUSACHes.Add(this);
						this._MATHELOAI = value.MATHELOAI;
					}
					else
					{
						this._MATHELOAI = default(string);
					}
					this.SendPropertyChanged("THELOAI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPMs(CTPM entity)
		{
			this.SendPropertyChanging();
			entity.DAUSACH = this;
		}
		
		private void detach_CTPMs(CTPM entity)
		{
			this.SendPropertyChanging();
			entity.DAUSACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOCGIA")]
	public partial class DOCGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADOCGIA;
		
		private string _TENDOCGIA;
		
		private string _DIACHI;
		
		private string _SDTDOCGIA;
		
		private string _EMAIL;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private EntitySet<THEDOCGIA> _THEDOCGIAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADOCGIAChanging(string value);
    partial void OnMADOCGIAChanged();
    partial void OnTENDOCGIAChanging(string value);
    partial void OnTENDOCGIAChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSDTDOCGIAChanging(string value);
    partial void OnSDTDOCGIAChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    #endregion
		
		public DOCGIA()
		{
			this._THEDOCGIAs = new EntitySet<THEDOCGIA>(new Action<THEDOCGIA>(this.attach_THEDOCGIAs), new Action<THEDOCGIA>(this.detach_THEDOCGIAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADOCGIA", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADOCGIA
		{
			get
			{
				return this._MADOCGIA;
			}
			set
			{
				if ((this._MADOCGIA != value))
				{
					this.OnMADOCGIAChanging(value);
					this.SendPropertyChanging();
					this._MADOCGIA = value;
					this.SendPropertyChanged("MADOCGIA");
					this.OnMADOCGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDOCGIA", DbType="NVarChar(30)")]
		public string TENDOCGIA
		{
			get
			{
				return this._TENDOCGIA;
			}
			set
			{
				if ((this._TENDOCGIA != value))
				{
					this.OnTENDOCGIAChanging(value);
					this.SendPropertyChanging();
					this._TENDOCGIA = value;
					this.SendPropertyChanged("TENDOCGIA");
					this.OnTENDOCGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTDOCGIA", DbType="Char(10)")]
		public string SDTDOCGIA
		{
			get
			{
				return this._SDTDOCGIA;
			}
			set
			{
				if ((this._SDTDOCGIA != value))
				{
					this.OnSDTDOCGIAChanging(value);
					this.SendPropertyChanging();
					this._SDTDOCGIA = value;
					this.SendPropertyChanged("SDTDOCGIA");
					this.OnSDTDOCGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(30)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOCGIA_THEDOCGIA", Storage="_THEDOCGIAs", ThisKey="MADOCGIA", OtherKey="MADOCGIA")]
		public EntitySet<THEDOCGIA> THEDOCGIAs
		{
			get
			{
				return this._THEDOCGIAs;
			}
			set
			{
				this._THEDOCGIAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THEDOCGIAs(THEDOCGIA entity)
		{
			this.SendPropertyChanging();
			entity.DOCGIA = this;
		}
		
		private void detach_THEDOCGIAs(THEDOCGIA entity)
		{
			this.SendPropertyChanging();
			entity.DOCGIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _HOTENNV;
		
		private string _GIOITINHNV;
		
		private System.Nullable<System.DateTime> _NGAYSINHNV;
		
		private string _DIACHINV;
		
		private string _DIENTHOAINV;
		
		private string _EMAILNV;
		
		private EntitySet<PHIEUMUONTRA> _PHIEUMUONTRAs;
		
		private EntitySet<THEDOCGIA> _THEDOCGIAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnHOTENNVChanging(string value);
    partial void OnHOTENNVChanged();
    partial void OnGIOITINHNVChanging(string value);
    partial void OnGIOITINHNVChanged();
    partial void OnNGAYSINHNVChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHNVChanged();
    partial void OnDIACHINVChanging(string value);
    partial void OnDIACHINVChanged();
    partial void OnDIENTHOAINVChanging(string value);
    partial void OnDIENTHOAINVChanged();
    partial void OnEMAILNVChanging(string value);
    partial void OnEMAILNVChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._PHIEUMUONTRAs = new EntitySet<PHIEUMUONTRA>(new Action<PHIEUMUONTRA>(this.attach_PHIEUMUONTRAs), new Action<PHIEUMUONTRA>(this.detach_PHIEUMUONTRAs));
			this._THEDOCGIAs = new EntitySet<THEDOCGIA>(new Action<THEDOCGIA>(this.attach_THEDOCGIAs), new Action<THEDOCGIA>(this.detach_THEDOCGIAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENNV", DbType="NVarChar(30)")]
		public string HOTENNV
		{
			get
			{
				return this._HOTENNV;
			}
			set
			{
				if ((this._HOTENNV != value))
				{
					this.OnHOTENNVChanging(value);
					this.SendPropertyChanging();
					this._HOTENNV = value;
					this.SendPropertyChanged("HOTENNV");
					this.OnHOTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINHNV", DbType="NVarChar(30)")]
		public string GIOITINHNV
		{
			get
			{
				return this._GIOITINHNV;
			}
			set
			{
				if ((this._GIOITINHNV != value))
				{
					this.OnGIOITINHNVChanging(value);
					this.SendPropertyChanging();
					this._GIOITINHNV = value;
					this.SendPropertyChanged("GIOITINHNV");
					this.OnGIOITINHNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINHNV", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINHNV
		{
			get
			{
				return this._NGAYSINHNV;
			}
			set
			{
				if ((this._NGAYSINHNV != value))
				{
					this.OnNGAYSINHNVChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINHNV = value;
					this.SendPropertyChanged("NGAYSINHNV");
					this.OnNGAYSINHNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHINV", DbType="NVarChar(100)")]
		public string DIACHINV
		{
			get
			{
				return this._DIACHINV;
			}
			set
			{
				if ((this._DIACHINV != value))
				{
					this.OnDIACHINVChanging(value);
					this.SendPropertyChanging();
					this._DIACHINV = value;
					this.SendPropertyChanged("DIACHINV");
					this.OnDIACHINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAINV", DbType="Char(10)")]
		public string DIENTHOAINV
		{
			get
			{
				return this._DIENTHOAINV;
			}
			set
			{
				if ((this._DIENTHOAINV != value))
				{
					this.OnDIENTHOAINVChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAINV = value;
					this.SendPropertyChanged("DIENTHOAINV");
					this.OnDIENTHOAINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAILNV", DbType="NVarChar(50)")]
		public string EMAILNV
		{
			get
			{
				return this._EMAILNV;
			}
			set
			{
				if ((this._EMAILNV != value))
				{
					this.OnEMAILNVChanging(value);
					this.SendPropertyChanging();
					this._EMAILNV = value;
					this.SendPropertyChanged("EMAILNV");
					this.OnEMAILNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUMUONTRA", Storage="_PHIEUMUONTRAs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<PHIEUMUONTRA> PHIEUMUONTRAs
		{
			get
			{
				return this._PHIEUMUONTRAs;
			}
			set
			{
				this._PHIEUMUONTRAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_THEDOCGIA", Storage="_THEDOCGIAs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<THEDOCGIA> THEDOCGIAs
		{
			get
			{
				return this._THEDOCGIAs;
			}
			set
			{
				this._THEDOCGIAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUMUONTRAs(PHIEUMUONTRA entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_PHIEUMUONTRAs(PHIEUMUONTRA entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_THEDOCGIAs(THEDOCGIA entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_THEDOCGIAs(THEDOCGIA entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHAXUATBAN")]
	public partial class NHAXUATBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANXB;
		
		private string _TENNXB;
		
		private string _DIACHINXB;
		
		private string _DIENTHOAIXB;
		
		private EntitySet<DAUSACH> _DAUSACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANXBChanging(string value);
    partial void OnMANXBChanged();
    partial void OnTENNXBChanging(string value);
    partial void OnTENNXBChanged();
    partial void OnDIACHINXBChanging(string value);
    partial void OnDIACHINXBChanged();
    partial void OnDIENTHOAIXBChanging(string value);
    partial void OnDIENTHOAIXBChanged();
    #endregion
		
		public NHAXUATBAN()
		{
			this._DAUSACHes = new EntitySet<DAUSACH>(new Action<DAUSACH>(this.attach_DAUSACHes), new Action<DAUSACH>(this.detach_DAUSACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANXB", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANXB
		{
			get
			{
				return this._MANXB;
			}
			set
			{
				if ((this._MANXB != value))
				{
					this.OnMANXBChanging(value);
					this.SendPropertyChanging();
					this._MANXB = value;
					this.SendPropertyChanged("MANXB");
					this.OnMANXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNXB", DbType="NVarChar(30)")]
		public string TENNXB
		{
			get
			{
				return this._TENNXB;
			}
			set
			{
				if ((this._TENNXB != value))
				{
					this.OnTENNXBChanging(value);
					this.SendPropertyChanging();
					this._TENNXB = value;
					this.SendPropertyChanged("TENNXB");
					this.OnTENNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHINXB", DbType="NVarChar(100)")]
		public string DIACHINXB
		{
			get
			{
				return this._DIACHINXB;
			}
			set
			{
				if ((this._DIACHINXB != value))
				{
					this.OnDIACHINXBChanging(value);
					this.SendPropertyChanging();
					this._DIACHINXB = value;
					this.SendPropertyChanged("DIACHINXB");
					this.OnDIACHINXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAIXB", DbType="Char(10)")]
		public string DIENTHOAIXB
		{
			get
			{
				return this._DIENTHOAIXB;
			}
			set
			{
				if ((this._DIENTHOAIXB != value))
				{
					this.OnDIENTHOAIXBChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAIXB = value;
					this.SendPropertyChanged("DIENTHOAIXB");
					this.OnDIENTHOAIXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHAXUATBAN_DAUSACH", Storage="_DAUSACHes", ThisKey="MANXB", OtherKey="MANXB")]
		public EntitySet<DAUSACH> DAUSACHes
		{
			get
			{
				return this._DAUSACHes;
			}
			set
			{
				this._DAUSACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DAUSACHes(DAUSACH entity)
		{
			this.SendPropertyChanging();
			entity.NHAXUATBAN = this;
		}
		
		private void detach_DAUSACHes(DAUSACH entity)
		{
			this.SendPropertyChanging();
			entity.NHAXUATBAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUMUONTRA")]
	public partial class PHIEUMUONTRA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHIEUMUON;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
		private string _MANV;
		
		private string _MATHE;
		
		private string _MADOCGIA;
		
		private EntitySet<CTPM> _CTPMs;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<THEDOCGIA> _THEDOCGIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUMUONChanging(string value);
    partial void OnMAPHIEUMUONChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMATHEChanging(string value);
    partial void OnMATHEChanged();
    partial void OnMADOCGIAChanging(string value);
    partial void OnMADOCGIAChanged();
    #endregion
		
		public PHIEUMUONTRA()
		{
			this._CTPMs = new EntitySet<CTPM>(new Action<CTPM>(this.attach_CTPMs), new Action<CTPM>(this.detach_CTPMs));
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._THEDOCGIA = default(EntityRef<THEDOCGIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUMUON", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHIEUMUON
		{
			get
			{
				return this._MAPHIEUMUON;
			}
			set
			{
				if ((this._MAPHIEUMUON != value))
				{
					this.OnMAPHIEUMUONChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUMUON = value;
					this.SendPropertyChanged("MAPHIEUMUON");
					this.OnMAPHIEUMUONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MATHE
		{
			get
			{
				return this._MATHE;
			}
			set
			{
				if ((this._MATHE != value))
				{
					if (this._THEDOCGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHEChanging(value);
					this.SendPropertyChanging();
					this._MATHE = value;
					this.SendPropertyChanged("MATHE");
					this.OnMATHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADOCGIA", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MADOCGIA
		{
			get
			{
				return this._MADOCGIA;
			}
			set
			{
				if ((this._MADOCGIA != value))
				{
					if (this._THEDOCGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADOCGIAChanging(value);
					this.SendPropertyChanging();
					this._MADOCGIA = value;
					this.SendPropertyChanged("MADOCGIA");
					this.OnMADOCGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUMUONTRA_CTPM", Storage="_CTPMs", ThisKey="MAPHIEUMUON", OtherKey="MAPHIEUMUON")]
		public EntitySet<CTPM> CTPMs
		{
			get
			{
				return this._CTPMs;
			}
			set
			{
				this._CTPMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_PHIEUMUONTRA", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUMUONTRAs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUMUONTRAs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THEDOCGIA_PHIEUMUONTRA", Storage="_THEDOCGIA", ThisKey="MATHE,MADOCGIA", OtherKey="MATHE,MADOCGIA", IsForeignKey=true)]
		public THEDOCGIA THEDOCGIA
		{
			get
			{
				return this._THEDOCGIA.Entity;
			}
			set
			{
				THEDOCGIA previousValue = this._THEDOCGIA.Entity;
				if (((previousValue != value) 
							|| (this._THEDOCGIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THEDOCGIA.Entity = null;
						previousValue.PHIEUMUONTRAs.Remove(this);
					}
					this._THEDOCGIA.Entity = value;
					if ((value != null))
					{
						value.PHIEUMUONTRAs.Add(this);
						this._MATHE = value.MATHE;
						this._MADOCGIA = value.MADOCGIA;
					}
					else
					{
						this._MATHE = default(string);
						this._MADOCGIA = default(string);
					}
					this.SendPropertyChanged("THEDOCGIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPMs(CTPM entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUMUONTRA = this;
		}
		
		private void detach_CTPMs(CTPM entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUMUONTRA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TACGIA")]
	public partial class TACGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATACGIA;
		
		private string _TENTACGIA;
		
		private EntitySet<DAUSACH> _DAUSACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATACGIAChanging(string value);
    partial void OnMATACGIAChanged();
    partial void OnTENTACGIAChanging(string value);
    partial void OnTENTACGIAChanged();
    #endregion
		
		public TACGIA()
		{
			this._DAUSACHes = new EntitySet<DAUSACH>(new Action<DAUSACH>(this.attach_DAUSACHes), new Action<DAUSACH>(this.detach_DAUSACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATACGIA", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATACGIA
		{
			get
			{
				return this._MATACGIA;
			}
			set
			{
				if ((this._MATACGIA != value))
				{
					this.OnMATACGIAChanging(value);
					this.SendPropertyChanging();
					this._MATACGIA = value;
					this.SendPropertyChanged("MATACGIA");
					this.OnMATACGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTACGIA", DbType="NVarChar(30)")]
		public string TENTACGIA
		{
			get
			{
				return this._TENTACGIA;
			}
			set
			{
				if ((this._TENTACGIA != value))
				{
					this.OnTENTACGIAChanging(value);
					this.SendPropertyChanging();
					this._TENTACGIA = value;
					this.SendPropertyChanged("TENTACGIA");
					this.OnTENTACGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TACGIA_DAUSACH", Storage="_DAUSACHes", ThisKey="MATACGIA", OtherKey="MATACGIA")]
		public EntitySet<DAUSACH> DAUSACHes
		{
			get
			{
				return this._DAUSACHes;
			}
			set
			{
				this._DAUSACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DAUSACHes(DAUSACH entity)
		{
			this.SendPropertyChanging();
			entity.TACGIA = this;
		}
		
		private void detach_DAUSACHes(DAUSACH entity)
		{
			this.SendPropertyChanging();
			entity.TACGIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TENTAIKHOAN;
		
		private string _MATKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTENTAIKHOANChanging(string value);
    partial void OnTENTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    #endregion
		
		public TAIKHOAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTAIKHOAN", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TENTAIKHOAN
		{
			get
			{
				return this._TENTAIKHOAN;
			}
			set
			{
				if ((this._TENTAIKHOAN != value))
				{
					this.OnTENTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TENTAIKHOAN = value;
					this.SendPropertyChanged("TENTAIKHOAN");
					this.OnTENTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="VarChar(20)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THEDOCGIA")]
	public partial class THEDOCGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _MATHE;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
		private System.Nullable<System.DateTime> _NGAYHETHAN;
		
		private string _MADOCGIA;
		
		private EntitySet<PHIEUMUONTRA> _PHIEUMUONTRAs;
		
		private EntityRef<DOCGIA> _DOCGIA;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMATHEChanging(string value);
    partial void OnMATHEChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    partial void OnNGAYHETHANChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYHETHANChanged();
    partial void OnMADOCGIAChanging(string value);
    partial void OnMADOCGIAChanged();
    #endregion
		
		public THEDOCGIA()
		{
			this._PHIEUMUONTRAs = new EntitySet<PHIEUMUONTRA>(new Action<PHIEUMUONTRA>(this.attach_PHIEUMUONTRAs), new Action<PHIEUMUONTRA>(this.detach_PHIEUMUONTRAs));
			this._DOCGIA = default(EntityRef<DOCGIA>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHE", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHE
		{
			get
			{
				return this._MATHE;
			}
			set
			{
				if ((this._MATHE != value))
				{
					this.OnMATHEChanging(value);
					this.SendPropertyChanging();
					this._MATHE = value;
					this.SendPropertyChanged("MATHE");
					this.OnMATHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYHETHAN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYHETHAN
		{
			get
			{
				return this._NGAYHETHAN;
			}
			set
			{
				if ((this._NGAYHETHAN != value))
				{
					this.OnNGAYHETHANChanging(value);
					this.SendPropertyChanging();
					this._NGAYHETHAN = value;
					this.SendPropertyChanged("NGAYHETHAN");
					this.OnNGAYHETHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADOCGIA", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADOCGIA
		{
			get
			{
				return this._MADOCGIA;
			}
			set
			{
				if ((this._MADOCGIA != value))
				{
					if (this._DOCGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADOCGIAChanging(value);
					this.SendPropertyChanging();
					this._MADOCGIA = value;
					this.SendPropertyChanged("MADOCGIA");
					this.OnMADOCGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THEDOCGIA_PHIEUMUONTRA", Storage="_PHIEUMUONTRAs", ThisKey="MATHE,MADOCGIA", OtherKey="MATHE,MADOCGIA")]
		public EntitySet<PHIEUMUONTRA> PHIEUMUONTRAs
		{
			get
			{
				return this._PHIEUMUONTRAs;
			}
			set
			{
				this._PHIEUMUONTRAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOCGIA_THEDOCGIA", Storage="_DOCGIA", ThisKey="MADOCGIA", OtherKey="MADOCGIA", IsForeignKey=true)]
		public DOCGIA DOCGIA
		{
			get
			{
				return this._DOCGIA.Entity;
			}
			set
			{
				DOCGIA previousValue = this._DOCGIA.Entity;
				if (((previousValue != value) 
							|| (this._DOCGIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOCGIA.Entity = null;
						previousValue.THEDOCGIAs.Remove(this);
					}
					this._DOCGIA.Entity = value;
					if ((value != null))
					{
						value.THEDOCGIAs.Add(this);
						this._MADOCGIA = value.MADOCGIA;
					}
					else
					{
						this._MADOCGIA = default(string);
					}
					this.SendPropertyChanged("DOCGIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_THEDOCGIA", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.THEDOCGIAs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.THEDOCGIAs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUMUONTRAs(PHIEUMUONTRA entity)
		{
			this.SendPropertyChanging();
			entity.THEDOCGIA = this;
		}
		
		private void detach_PHIEUMUONTRAs(PHIEUMUONTRA entity)
		{
			this.SendPropertyChanging();
			entity.THEDOCGIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THELOAI")]
	public partial class THELOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHELOAI;
		
		private string _TENTHELOAI;
		
		private EntitySet<DAUSACH> _DAUSACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHELOAIChanging(string value);
    partial void OnMATHELOAIChanged();
    partial void OnTENTHELOAIChanging(string value);
    partial void OnTENTHELOAIChanged();
    #endregion
		
		public THELOAI()
		{
			this._DAUSACHes = new EntitySet<DAUSACH>(new Action<DAUSACH>(this.attach_DAUSACHes), new Action<DAUSACH>(this.detach_DAUSACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHELOAI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHELOAI
		{
			get
			{
				return this._MATHELOAI;
			}
			set
			{
				if ((this._MATHELOAI != value))
				{
					this.OnMATHELOAIChanging(value);
					this.SendPropertyChanging();
					this._MATHELOAI = value;
					this.SendPropertyChanged("MATHELOAI");
					this.OnMATHELOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHELOAI", DbType="NVarChar(30)")]
		public string TENTHELOAI
		{
			get
			{
				return this._TENTHELOAI;
			}
			set
			{
				if ((this._TENTHELOAI != value))
				{
					this.OnTENTHELOAIChanging(value);
					this.SendPropertyChanging();
					this._TENTHELOAI = value;
					this.SendPropertyChanged("TENTHELOAI");
					this.OnTENTHELOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THELOAI_DAUSACH", Storage="_DAUSACHes", ThisKey="MATHELOAI", OtherKey="MATHELOAI")]
		public EntitySet<DAUSACH> DAUSACHes
		{
			get
			{
				return this._DAUSACHes;
			}
			set
			{
				this._DAUSACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DAUSACHes(DAUSACH entity)
		{
			this.SendPropertyChanging();
			entity.THELOAI = this;
		}
		
		private void detach_DAUSACHes(DAUSACH entity)
		{
			this.SendPropertyChanging();
			entity.THELOAI = null;
		}
	}
	
	public partial class procSachDuocMuonNhieuResult
	{
		
		private string _MASACH;
		
		private string _TENSACH;
		
		private string _NAMXUATBAN;
		
		private string _MATHELOAI;
		
		private string _MANXB;
		
		private string _MATACGIA;
		
		private System.Nullable<int> _maxMaSachCnt;
		
		public procSachDuocMuonNhieuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASACH", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MASACH
		{
			get
			{
				return this._MASACH;
			}
			set
			{
				if ((this._MASACH != value))
				{
					this._MASACH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSACH", DbType="NVarChar(30)")]
		public string TENSACH
		{
			get
			{
				return this._TENSACH;
			}
			set
			{
				if ((this._TENSACH != value))
				{
					this._TENSACH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMXUATBAN", DbType="Char(5)")]
		public string NAMXUATBAN
		{
			get
			{
				return this._NAMXUATBAN;
			}
			set
			{
				if ((this._NAMXUATBAN != value))
				{
					this._NAMXUATBAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHELOAI", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MATHELOAI
		{
			get
			{
				return this._MATHELOAI;
			}
			set
			{
				if ((this._MATHELOAI != value))
				{
					this._MATHELOAI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANXB", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MANXB
		{
			get
			{
				return this._MANXB;
			}
			set
			{
				if ((this._MANXB != value))
				{
					this._MANXB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATACGIA", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MATACGIA
		{
			get
			{
				return this._MATACGIA;
			}
			set
			{
				if ((this._MATACGIA != value))
				{
					this._MATACGIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxMaSachCnt", DbType="Int")]
		public System.Nullable<int> maxMaSachCnt
		{
			get
			{
				return this._maxMaSachCnt;
			}
			set
			{
				if ((this._maxMaSachCnt != value))
				{
					this._maxMaSachCnt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
